apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: ivaquero/simple-webhook:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "20Mi"
            cpu: "100m"
        ports:
          - containerPort: 8080
            name: http
