apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.20.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "55Mi"
            cpu: "200m"
        ports:
          - containerPort: 9093
            name: http
        volumeMounts:
          - name: alertmanager-config
            mountPath: /etc/alertmanager
      volumes:
        - name: alertmanager-config
          configMap:
              name: alertmanager-config
